// apps/react/src/App.tsx
import { Link, Outlet } from 'react-router-dom';

export const App = () => {
  return (
    <div className="flex justify-center pt-4">
      <div className="max-w-xl w-full space-y-4">
        <div className="bg-slate-100 rounded-md flex items-center justify-between p-3">
          <span className="text-slate-700">You are not signed in.</span>
          <Link
            to="/signin"
            className="bg-blue-600 text-white py-1.5 px-4 rounded-md"
          >
            Sign in
          </Link>
        </div>

        <ul className="flex items-center gap-2 [&>li]:text-slate-700 [&>li]:underline [&>li]:underline-offset-2">
          <li>
            <Link to="/">Home</Link>
          </li>
          <li>
            <Link to="/protected">Protected</Link>
          </li>
        </ul>

        <Outlet />
      </div>
    </div>
  );
};

export const Index = () => {
  return (
    <div className="space-y-1 pt-4">
      <h1 className="text-2xl font-bold">React/Express/Auth.js Example</h1>
      <p className="text-slate-500">
        This is an example of how to use React with Express and Auth.js
      </p>
    </div>
  );
};

export const Protected = () => {
  return (
    <div className="space-y-1 pt-4">
      <h1 className="text-2xl font-bold">Protected route</h1>
      <p className="text-slate-500">This route is protected. Session.</p>
    </div>
  );
};

export const SignIn = () => {
  return (
    <div className="flex justify-center pt-4">
      <div className="max-w-xl w-full space-y-4">
        <Link to="/" className="text-slate-500 text-sm">
          &larr; Go back to Home page
        </Link>
        <div className="bg-slate-100 rounded-md flex items-center justify-between p-3">
          Sign in
        </div>
      </div>
    </div>
  );
};

// apps/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: `<router-outlet />`,
})
export class AppComponent {}

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [RouterOutlet, RouterLink],
  template: `
    <header class="py-4 flex flex-col items-center [&>*]:max-w-xl [&>*]:w-full">
      <div
        class="bg-slate-200 rounded-md p-4 text-slate-700 flex items-center justify-between"
      >
        <span>You are not logged in</span>
        <a
          routerLink="/signin"
          class="bg-blue-500 text-white py-1.5 px-3 rounded-md"
          >Sign in</a
        >
      </div>
      <nav
        class="p-4 flex items-center gap-2 [&>*]:underline [&>*]:underline-offset-2"
      >
        <a routerLink="/" class="text-blue-500">Home</a>
        <a routerLink="/protected" class="text-blue-500">Protected</a>
      </nav>
    </header>
    <router-outlet />
  `,
})
export class LayoutComponent {}

@Component({
  selector: 'app-index',
  standalone: true,
  template: `
    <div class="flex justify-center">
      <div class="max-w-xl w-full p-4 text-slate-700 flex flex-col gap-1">
        <h1 class="text-2xl font-bold">Angular/Express/Auth.js Example</h1>
        <span class="text-slate-500">
          This is a simple example of how to use Angular with Express and
          Auth.js.
        </span>
      </div>
    </div>
  `,
})
export class IndexComponent {}

@Component({
  selector: 'app-protected',
  standalone: true,
  template: `
    <div class="flex justify-center">
      <div class="max-w-xl w-full p-4 text-slate-700 flex flex-col gap-1">
        <h1 class="text-2xl font-bold">Protected component</h1>
        <span class="text-slate-500"> This is a protected component. </span>
      </div>
    </div>
  `,
})
export class ProtectedComponent {}

@Component({
  selector: 'app-signin',
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="flex justify-center">
      <div class="max-w-xl w-full p-4 text-slate-700 space-y-2">
        <a routerLink="/" class="text-blue-500">&larr; Go back to Home page</a>
        <div
          class="bg-slate-200 max-w-xl w-full rounded-md p-4 text-slate-700 flex items-center justify-between"
        >
          <span
            class="bg-blue-500 text-white py-1.5 px-3 rounded-md cursor-pointer"
            >Sign in with Google</span
          >
        </div>
      </div>
    </div>
  `,
})
export class SignInComponent {}
