// apps/angular/src/app/app.component.ts
import { Component, inject } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';
import { AuthService } from './auth/auth.service';
import { AsyncPipe } from '@angular/common';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: `<router-outlet />`,
})
export class AppComponent {}

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [RouterOutlet, RouterLink, AsyncPipe],
  template: `
    <header class="py-4 flex flex-col items-center [&>*]:max-w-xl [&>*]:w-full">
      <div
        class="bg-slate-200 rounded-md p-4 text-slate-700 flex items-center justify-between"
      >
        @if (auth.session$ | async; as session) {
        <span>{{ session.user.email }}</span>
        <button
          (click)="signOut()"
          class="bg-blue-500 text-white py-1.5 px-3 rounded-md"
        >
          Sign out
        </button>
        } @else {
        <span>You are not logged in</span>
        <a
          routerLink="/signin"
          class="bg-blue-500 text-white py-1.5 px-3 rounded-md"
          >Sign in</a
        >
        }
      </div>
      <nav
        class="p-4 flex items-center gap-2 [&>*]:underline [&>*]:underline-offset-2"
      >
        <a routerLink="/" class="text-blue-500">Home</a>
        <a routerLink="/protected" class="text-blue-500">Protected</a>
      </nav>
    </header>
    <router-outlet />
  `,
})
export class LayoutComponent {
  public auth = inject(AuthService);

  signOut() {
    this.auth.signOut().subscribe();
  }
}

@Component({
  selector: 'app-index',
  standalone: true,
  template: `
    <div class="flex justify-center">
      <div class="max-w-xl w-full p-4 text-slate-700 flex flex-col gap-1">
        <h1 class="text-2xl font-bold">Angular/Express/Auth.js Example</h1>
        <span class="text-slate-500">
          This is a simple example of how to use Angular with Express and
          Auth.js.
        </span>
      </div>
    </div>
  `,
})
export class IndexComponent {}

@Component({
  selector: 'app-protected',
  standalone: true,
  template: `
    <div class="flex justify-center">
      <div class="max-w-xl w-full p-4 text-slate-700 flex flex-col gap-1">
        <h1 class="text-2xl font-bold">Protected component</h1>
        <span class="text-slate-500"> This is a protected component. </span>
      </div>
    </div>
  `,
})
export class ProtectedComponent {}

@Component({
  selector: 'app-signin',
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="flex justify-center">
      <div class="max-w-xl w-full p-4 text-slate-700 space-y-2">
        <a routerLink="/" class="text-blue-500">&larr; Go back to Home page</a>
        <div
          class="bg-slate-200 max-w-xl w-full rounded-md p-4 text-slate-700 flex items-center justify-between"
        >
          <button
            class="bg-blue-500 text-white py-1.5 px-3 rounded-md cursor-pointer"
            (click)="signIn()"
          >
            Sign in with Google
          </button>
        </div>
      </div>
    </div>
  `,
})
export class SignInComponent {
  private auth = inject(AuthService);

  signIn() {
    this.auth.signIn('google').subscribe();
  }
}

// apps/react/src/app.tsx
import { Link, Navigate, Outlet, useOutletContext } from 'react-router-dom';
import { useAuth } from './lib/authjs/useAuth';
import { useEffect, useState } from 'react';
import { getSession } from './lib/authjs/auth';
import { UserInfo } from './lib/authjs/types';

export const App = () => {
  const [userInfo, setUserInfo] = useState<UserInfo>(null);
  const { logout } = useAuth();

  useEffect(() => {
    const getUserData = async () => {
      const userInfo = await getSession();
      setUserInfo(userInfo);
    };

    getUserData();
  }, []);

  return (
    <div className="flex justify-center pt-4">
      <div className="max-w-xl w-full space-y-4">
        <div className="bg-slate-100 rounded-md flex items-center justify-between p-3">
          <span className="text-slate-700">
            {userInfo ? userInfo.user?.email : 'You are not signed in.'}
          </span>
          {userInfo ? (
            <button
              className="bg-blue-600 text-white py-1.5 px-4 rounded-md"
              onClick={logout}
            >
              Sign out
            </button>
          ) : (
            <Link
              to="/signin"
              className="bg-blue-600 text-white py-1.5 px-4 rounded-md"
            >
              Sign in
            </Link>
          )}
        </div>

        <ul className="flex items-center gap-2 [&>li]:text-slate-700 [&>li]:underline [&>li]:underline-offset-2">
          <li>
            <Link to="/">Home</Link>
          </li>
          <li>
            <Link to="/protected">Protected</Link>
          </li>
        </ul>

        <Outlet context={{ userInfo }} />
      </div>
    </div>
  );
};

export const Index = () => {
  return (
    <div className="space-y-1 pt-4">
      <h1 className="text-2xl font-bold">React/Express/Auth.js Example</h1>
      <p className="text-slate-500">
        This is an example of how to use React with Express and Auth.js
      </p>
    </div>
  );
};

export const Protected = () => {
  const { userInfo } = useOutletContext<{ userInfo: UserInfo }>();

  return userInfo ? (
    <div className="space-y-1 pt-4">
      <h1 className="text-2xl font-bold">Protected route</h1>
      <p className="text-slate-500">This route is protected. Session.</p>
    </div>
  ) : (
    <Navigate to="/signin" />
  );
};

export const SignIn = () => {
  const { loginWithOAuth } = useAuth();

  return (
    <div className="flex justify-center pt-4">
      <div className="max-w-xl w-full space-y-4">
        <Link to="/" className="text-slate-500 text-sm">
          &larr; Go back to Home page
        </Link>
        <div className="bg-slate-100 rounded-md flex items-center justify-between p-3">
          <button
            className="px-3 py-1.5 bg-blue-500 text-white rounded-md"
            onClick={() => loginWithOAuth('google')}
          >
            Sign in with Google
          </button>
        </div>
      </div>
    </div>
  );
};
